import {
    SiReact,
    SiNodedotjs,
    SiDocker,
    SiMongodb,
    SiJenkins,
    SiGithubactions,
    SiAmazon,
    SiGnubash,
    SiKubernetes,
    SiTerraform,
    SiPrometheus,
    SiGrafana,
    SiHelm,
    SiHostinger,
    SiLinux,
    SiAnsible,
    SiGit,
    SiPython,
    SiJavascript,
    SiGo,
    SiNextdotjs,
    SiTailwindcss,
    SiJsonwebtokens,
    SiGoogle,
    SiRazorpay,
    SiCloudflare,
    SiPostgresql,
    SiGooglegemini,
    SiOpenai,
    SiExpress,
    SiRedis,
    SiDjango,
    SiHtml5,
    SiCss3,
    SiCloudinary,
    SiAuth0,
    SiMysql,
    SiGooglecloud,
    SiPhp,
    SiTypescript,
    SiBun,
    SiPrisma,
    SiTurborepo,
    SiSentry,
    SiSocketdotio,
    SiWebrtc,
    SiNginx,
    SiRedux,
    SiReactrouter,
    SiZod,
    SiGooglemaps,
    SiMarkdown,
    SiTelegram,
    SiWhatsapp,
    SiElasticsearch,
    SiFfmpeg,
    SiHono,
    SiTrpc,
    SiGraphql,
    SiReactquery,
    SiApachekafka,
    SiPuppeteer
} from 'react-icons/si';
import { FaDatabase, FaServer, FaCode, FaLock, FaTruck, FaVideo, FaRobot, FaEnvelope, FaBrain, FaTerminal, FaSearch } from 'react-icons/fa';
import { IconType } from 'react-icons';

export interface TechIcon {
    icon: IconType;
    color: string;
    isFallback?: boolean;
}

const techIconMap: { [key: string]: TechIcon } = {
    // Operations / Experience
    "ReactJS": { icon: SiReact, color: "#61DAFB" },
    "NodeJS": { icon: SiNodedotjs, color: "#339933" },
    "Docker": { icon: SiDocker, color: "#2496ED" },
    "Hostinger": { icon: SiHostinger, color: "#673DE6" },
    "MongoDB": { icon: SiMongodb, color: "#47A248" },
    "Puppeteer": { icon: SiPuppeteer, color: "#00D8A2" },

    // Projects
    "Jenkins": { icon: SiJenkins, color: "#D24939" },
    "GitHub Actions": { icon: SiGithubactions, color: "#2088FF" },
    "AWS": { icon: SiAmazon, color: "#FF9900" },
    "Bash": { icon: SiGnubash, color: "#4EAA25" },
    "Kubernetes": { icon: SiKubernetes, color: "#326CE5" },
    "AWS EKS": { icon: SiAmazon, color: "#FF9900" },
    "Terraform": { icon: SiTerraform, color: "#7B42BC" },
    "Prometheus": { icon: SiPrometheus, color: "#E6522C" },
    "Grafana": { icon: SiGrafana, color: "#F46800" },
    "Helm": { icon: SiHelm, color: "#0F1689" },
    "HCL": { icon: SiTerraform, color: "#7B42BC" },
    "State Management": { icon: FaDatabase, color: "#A0A0A0" },

    // Others / Fallbacks
    "Python": { icon: SiPython, color: "#3776AB" },
    "JavaScript": { icon: SiJavascript, color: "#F7DF1E" },
    "Go": { icon: SiGo, color: "#00ADD8" },
    "Next.js": { icon: SiNextdotjs, color: "#000000" },
    "Linux": { icon: SiLinux, color: "#FCC624" },
    "Git": { icon: SiGit, color: "#F05032" },
    "Ansible": { icon: SiAnsible, color: "#EE0000" },

    // Freelance / New
    "Tailwind CSS": { icon: SiTailwindcss, color: "#06B6D4" },
    "JWT": { icon: SiJsonwebtokens, color: "#000000" },
    "Google OAuth": { icon: SiGoogle, color: "#4285F4" },
    "Razorpay": { icon: SiRazorpay, color: "#3395FF" },
    "Cloudflare": { icon: SiCloudflare, color: "#F38020" },
    "Cloudflare Turnstile": { icon: SiCloudflare, color: "#F38020" },
    "Google reCAPTCHA v3": { icon: SiGoogle, color: "#4285F4" },
    "PostgreSQL": { icon: SiPostgresql, color: "#4169E1" },
    "Gemini AI": { icon: SiGooglegemini, color: "#8E75B2" },
    "Groq AI API": { icon: SiOpenai, color: "#412991" },
    "Shiprocket": { icon: FaTruck, color: "#E02128" },
    "HLS": { icon: FaVideo, color: "#FF8800" },
    "Microservices": { icon: FaServer, color: "#333333" },
    "AES Encryption": { icon: FaLock, color: "#A0A0A0" },
    "Web Worker": { icon: FaTerminal, color: "#F7DF1E" },
    "Express.js": { icon: SiExpress, color: "#000000" },
    "CI/CD": { icon: SiGithubactions, color: "#2088FF" },
    "Moltbot": { icon: FaRobot, color: "#ff4d4d" },

    // Fixes/Aliases
    "React.js": { icon: SiReact, color: "#61DAFB" },
    "Node.js": { icon: SiNodedotjs, color: "#339933" },
    "Redis": { icon: SiRedis, color: "#DC382D" },
    "Redis Pub/Sub": { icon: SiRedis, color: "#DC382D" },
    "BullMQ": { icon: SiRedis, color: "#DC382D" },
    "Resend.com": { icon: FaEnvelope, color: "#000000" },
    "Turnstile": { icon: SiCloudflare, color: "#F38020" },
    "OAuth": { icon: SiAuth0, color: "#EB5424" },
    "OAuth 2.0": { icon: SiAuth0, color: "#EB5424" },
    "reCAPTCHA": { icon: SiGoogle, color: "#4285F4" },
    "Cloudinary": { icon: SiCloudinary, color: "#3448C5" },
    "Django": { icon: SiDjango, color: "#092E20" },
    "HTML": { icon: SiHtml5, color: "#E34F26" },
    "CSS": { icon: SiCss3, color: "#1572B6" },
    "MySQL": { icon: SiMysql, color: "#4479A1" },
    "Google Cloud Platform (GCP)": { icon: SiGooglecloud, color: "#4285F4" },
    "GCP": { icon: SiGooglecloud, color: "#4285F4" },
    "Postgres": { icon: SiPostgresql, color: "#4169E1" },
    "Large Language Models (LLM)": { icon: FaBrain, color: "#9046FF" },
    "PHP": { icon: SiPhp, color: "#777BB4" },
    "pubsub": { icon: SiRedis, color: "#DC382D" },

    // Roadmap additions
    "TypeScript": { icon: SiTypescript, color: "#3178C6" },
    "TypeScript 5+": { icon: SiTypescript, color: "#3178C6" },
    "Strict Mode": { icon: SiTypescript, color: "#3178C6" },
    "Generics": { icon: SiTypescript, color: "#3178C6" },
    "Type Declarations": { icon: SiTypescript, color: "#3178C6" },
    "Bun": { icon: SiBun, color: "#FBF0DF" },
    "Hono": { icon: SiHono, color: "#E36002" },
    "Prisma": { icon: SiPrisma, color: "#2D3748" },
    "Prisma ORM": { icon: SiPrisma, color: "#2D3748" },
    "Turborepo": { icon: SiTurborepo, color: "#EF4444" },
    "Sentry": { icon: SiSentry, color: "#362D59" },
    "Socket.io": { icon: SiSocketdotio, color: "#010101" },
    "WebSockets": { icon: FaServer, color: "#010101" },
    "WebRTC": { icon: SiWebrtc, color: "#333333" },
    "HTML5": { icon: SiHtml5, color: "#E34F26" },
    "CSS3": { icon: SiCss3, color: "#1572B6" },
    "Flexbox/Grid": { icon: SiCss3, color: "#1572B6" },
    "ARIA": { icon: SiHtml5, color: "#E34F26" },
    "JavaScript ES6+": { icon: SiJavascript, color: "#F7DF1E" },
    "Fetch API": { icon: SiJavascript, color: "#F7DF1E" },
    "DOM APIs": { icon: SiJavascript, color: "#F7DF1E" },
    "LocalStorage": { icon: SiJavascript, color: "#F7DF1E" },
    "React 19": { icon: SiReact, color: "#61DAFB" },
    "Redux Toolkit/Zustand": { icon: SiRedux, color: "#764ABC" },
    "Redux Toolkit": { icon: SiRedux, color: "#764ABC" },
    "Zustand": { icon: SiReact, color: "#61DAFB" },
    "React Router": { icon: SiReactrouter, color: "#CA4245" },
    "Next.js App Router": { icon: SiNextdotjs, color: "#000000" },
    "NextAuth": { icon: SiNextdotjs, color: "#000000" },
    "Server Actions": { icon: SiNextdotjs, color: "#000000" },
    "ISR": { icon: SiNextdotjs, color: "#000000" },
    "Zod": { icon: SiZod, color: "#3E67B1" },
    "Rate Limiting": { icon: SiCloudflare, color: "#F38020" },
    "Cookies": { icon: FaLock, color: "#F7DF1E" },
    "Nginx": { icon: SiNginx, color: "#009639" },
    "AWS EC2/S3/CloudFront": { icon: SiAmazon, color: "#FF9900" },
    "AWS Lambda/MediaConvert": { icon: SiAmazon, color: "#FF9900" },

    // Additional requested brand mappings
    "Google Maps API": { icon: SiGooglemaps, color: "#4285F4" },
    "Google Maps": { icon: SiGooglemaps, color: "#4285F4" },
    "Cloudflare R2": { icon: SiCloudflare, color: "#F38020" },
    "Cloudflare Geolocation": { icon: SiCloudflare, color: "#F38020" },
    "Markdown": { icon: SiMarkdown, color: "#000000" },
    "AWS Lambda": { icon: SiAmazon, color: "#FF9900" },
    "ImageKit": { icon: SiCloudinary, color: "#3448C5" },
    "imagekit": { icon: SiCloudinary, color: "#3448C5" },
    "Groq AI": { icon: SiOpenai, color: "#412991" },
    "Groq API": { icon: SiOpenai, color: "#412991" },
    "Groq SDK": { icon: SiOpenai, color: "#412991" },
    "Groq": { icon: SiOpenai, color: "#412991" },
    "Telegram Bot": { icon: SiTelegram, color: "#26A5E4" },
    "Telegram": { icon: SiTelegram, color: "#26A5E4" },
    "WhatsApp Integration": { icon: SiWhatsapp, color: "#25D366" },
    "WhatsApp API": { icon: SiWhatsapp, color: "#25D366" },
    "WhatsApp": { icon: SiWhatsapp, color: "#25D366" },
    "Typesense": { icon: FaSearch, color: "#F60000" },
    "Elasticsearch": { icon: SiElasticsearch, color: "#005571" },
    "FFmpeg": { icon: SiFfmpeg, color: "#007808" },
    "Cloudflare Workers": { icon: SiCloudflare, color: "#F38020" },
    "AWS MediaConvert": { icon: SiAmazon, color: "#FF9900" },
    "AWS Elemental MediaConvert": { icon: SiAmazon, color: "#FF9900" },
    "Sharp": { icon: FaVideo, color: "#99CC00" },
    "tRPC": { icon: SiTrpc, color: "#2596BE" },
    "GraphQL": { icon: SiGraphql, color: "#E10098" },
    "TanStack Query": { icon: SiReactquery, color: "#FF4154" },
    "React Query": { icon: SiReactquery, color: "#FF4154" },
    "Apache Kafka": { icon: SiApachekafka, color: "#231F20" },
    "Kafka": { icon: SiApachekafka, color: "#231F20" }
};

export const getTechIcon = (techName: string): TechIcon => {
    // Direct match
    if (techIconMap[techName]) {
        return { ...techIconMap[techName], isFallback: false };
    }

    // Normalized match (case insensitive)
    const lowerName = techName.toLowerCase();
    const foundKey = Object.keys(techIconMap).find(key => key.toLowerCase() === lowerName);
    if (foundKey) {
        return { ...techIconMap[foundKey], isFallback: false };
    }

    // Default fallback (flagged as fallback so pages can suppress it if desired)
    return { icon: FaCode, color: "#888888", isFallback: true };
};
